### PR TITLE
[RELEASE] Release v0.2

### PR DESCRIPTION
**Pull request by ravinkohli**
This PR introduces support for time series forecasting tasks. Along with this, it also introduces new tabular feature preprocessors, along with bug fixes.

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

Note that a Pull Request should only contain one of refactoring, new features or documentation changes.
Please separate these changes and send us individual PRs for each.
For more information on how to create a good pull request, please refer to [The anatomy of a perfect pull request](https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067).

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

## Description

This PR includes changes from 
1. #285 - update to README.md.
2. #331, #334, #351 - adds function to visualise performance and statistics in base_task.
3.  #346,  #367 , #370 , #371 , #375, #384 , #386 , #382 , #388 - fixes various bugs
4. #373 , #372 , #376 , #378 - introduces new tabular feature preprocessors.
5. #368 - adds evaluator class to run with `NoResamplingStrategies`.
6. #387 , #398 - dataset compression via precision reduction and subsampling
7. #434 , #443 , #445 - introduces `TimeSeriesForecastingTask`.
8. #441 - adds functionality to pass feature types for a dataset.

### CODE REVIEW

**Review by dengdifan — APPROVED** [review]
Looks good to me. Thanks!

**Comment by ravinkohli** [comment]
>     * Changelog includes the PR's you mention

yeah, I have to update the documentation with the change log.

**Review by theodorju — APPROVED** [review]
Changes look good to me. Documentation and version numbering is correctly updated. Changelog is fixed in another PR. Thanks.

**Comment by ravinkohli** [comment]
> @ravinkohli Basically this PR is almost same as the one from Difan, right? I am wondering because the changes that I remember I made by myself are also included in this PR.

This PR includes all the changes between v0.1.1 to v0.2. So yes it includes code from those PRs as well.

**Pull request merged**
